### ISSUE TITLE
Compile warnings, and runtime errors in the browser

### ISSUE THREAD

**Issue by draeder** [tanayseven/playindoor.games#5]
I tried cloning your repo for local testing to help try to identify the problems you're having with Bugout, but I'm getting the following compile warnings:

```
Compiled with warnings.

src/Communication.ts
  Line 45:36:  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  Line 45:46:  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

src/TicTacToe/Screen.tsx
  Line 17:18:  'setGame' is assigned a value but never used           @typescript-eslint/no-unused-vars
  Line 21:27:  'setCommunication' is assigned a value but never used  @typescript-eslint/no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

In the browser, I'm getting the following errors:
```
Uncaught SyntaxError: Unexpected token '<'
0.chunk.js:1 Uncaught SyntaxError: Unexpected token '<'
main.chunk.js:1 Uncaught SyntaxError: Unexpected token '<'
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
```

**Comment by tanayseven** [comment]
Hey, thanks a lot for looking into the repo, please give me a couple of hours to fix those issues. Really appreciate it.

**Comment by tanayseven** [comment]
I've pushed the latest change to `master` which is free of errors or warnings on my side.

The only problem that I'm facing is that it takes several minutes to about an hour to connect while using my own tracker.

**Comment by draeder** [comment]
@tanayseven Thanks - It's compiling correctly now. I was able to confirm I was getting a connection to Bugout nearly immediately by adding in Communications.ts. 

```
        this.bugout.on('seen', (address) => {
            console.log('Got a new connection from', address)
        })
```

There seems to be other issues with your code in sending messages / handling received messages.

Note that sometimes Bugout does take a bit to register connections, but shouldn't take more than a minute or so. The more peers announcing the room, the faster connections occur.

**Comment by tanayseven** [comment]
Okay, thanks for looking into this issue, really appreciate it

**Comment by tanayseven** [comment]
Hey @draeder. Can I also use a few public trackers in addition to my own tracker?

**Comment by draeder** [comment]
@tanayseven Yes. Bugout will try announcing to all the trackers, but you will get warnings in the console on the browser for non-responsive ones.

**Comment by tanayseven** [comment]
@draeder cool, thanks. Will do that then. I think Compile warnings and runtime errors in the browser are eliminated now. So I'll close this issue.
